#ifndef __VERSION__
#define __VERSION__

#define TO_STRING_EXP(v) #v
#define TO_STRING(v)     TO_STRING_EXP(v)

#define VERSION_MAJOR    0
#define VERSION_MINOR    1
#define VERSION_REVISION 0

#define VERSION TO_STRING( VERSION_MAJOR ) "." TO_STRING( VERSION_MINOR ) "." TO_STRING( VERSION_REVISION )

#endif // __VERSION__